"""
Pairwise Image Comparison App

A Flask app for comparing SVG images generated by different models.
"""

import csv
import os
import random
from pathlib import Path

from flask import Flask, jsonify, render_template, request, send_from_directory

app = Flask(__name__)

BATCH_OUTPUTS_DIR = Path(__file__).parent / "batch_outputs"
COMPARISONS_CSV = Path(__file__).parent / "comparisons.csv"


def get_batch_folders():
    """Get list of batch folder names."""
    if not BATCH_OUTPUTS_DIR.exists():
        return []
    return sorted([d.name for d in BATCH_OUTPUTS_DIR.iterdir() if d.is_dir()])


def get_prompt_folders(batch_name: str):
    """Get list of prompt folders within a batch."""
    batch_path = BATCH_OUTPUTS_DIR / batch_name
    if not batch_path.exists():
        return []
    return [d for d in batch_path.iterdir() if d.is_dir()]


def get_png_files(folder: Path):
    """Get list of PNG files in a folder."""
    return [f for f in folder.iterdir() if f.suffix == ".png"]


def get_prompt_text(folder: Path):
    """Read the prompt text from a folder."""
    prompt_file = folder / "prompt.txt"
    if prompt_file.exists():
        return prompt_file.read_text().strip()
    return ""


def extract_model_name(filename: str):
    """Extract model name from filename (strip .svg extension)."""
    return filename.rsplit(".", 1)[0]


@app.route("/")
def index():
    """Serve the main comparison page."""
    return render_template("compare.html")


@app.route("/api/batches")
def api_batches():
    """Return list of available batch folders."""
    batches = get_batch_folders()
    return jsonify({"batches": batches})


@app.route("/api/pair")
def api_pair():
    """Get a random pair of SVG images from the specified batch."""
    batch = request.args.get("batch")
    if not batch:
        return jsonify({"error": "No batch specified"}), 400

    prompt_folders = get_prompt_folders(batch)
    if not prompt_folders:
        return jsonify({"error": "No prompt folders found"}), 404

    # Pick a random prompt folder
    folder = random.choice(prompt_folders)
    png_files = get_png_files(folder)

    if len(png_files) < 2:
        return jsonify({"error": "Not enough PNG files in folder"}), 404

    # Pick two random PNG files
    pair = random.sample(png_files, 2)
    prompt_text = get_prompt_text(folder)

    # Build relative paths for serving
    folder_rel = f"{batch}/{folder.name}"
    model_a = extract_model_name(pair[0].name)
    model_b = extract_model_name(pair[1].name)

    return jsonify({
        "folder_path": folder_rel,
        "model_a": model_a,
        "model_b": model_b,
        "image_a": f"/images/{folder_rel}/{pair[0].name}",
        "image_b": f"/images/{folder_rel}/{pair[1].name}",
        "prompt": prompt_text,
    })


@app.route("/api/vote", methods=["POST"])
def api_vote():
    """Record a vote to the CSV file."""
    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    folder_path = data.get("folder_path")
    model_a = data.get("model_a")
    model_b = data.get("model_b")
    winner = data.get("winner")

    if not all([folder_path, model_a, model_b, winner]):
        return jsonify({"error": "Missing required fields"}), 400

    if winner not in ("a", "b"):
        return jsonify({"error": "Winner must be 'a' or 'b'"}), 400

    # Write to CSV (create with header if doesn't exist)
    file_exists = COMPARISONS_CSV.exists()
    with open(COMPARISONS_CSV, "a", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["folder_path", "model_a", "model_b", "winner"])
        writer.writerow([folder_path, model_a, model_b, winner])

    return jsonify({"success": True})


@app.route("/images/<path:filepath>")
def serve_image(filepath):
    """Serve SVG images from batch_outputs directory."""
    return send_from_directory(BATCH_OUTPUTS_DIR, filepath)


if __name__ == "__main__":
    app.run(debug=True, port=5001)

